[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[deploy.environmentVariables]]
name = "USE_CHESS_API"
value = "true"

[[deploy.environmentVariables]]
name = "CHESS_API_URL"
value = "https://chess-api.com/v1"

[[deploy.environmentVariables]]
name = "GIN_MODE"
value = "release"

[[deploy.environmentVariables]]
name = "PORT"
value = "8080"
